language: cpp
sudo: required
dist: focal

os:
  - linux
#  - osx

before_install:
  - echo "$TRAVIS_OS_NAME"
  - if [[ "$TRAVIS_OS_NAME" = "linux" ]];then sudo apt-get install -qfy autoconf automake autotools-dev bison flex libicu-dev libreadline-dev libtool pkg-config python3-dev python3-setuptools swig zlib1g-dev; fi
  - if [[ "$TRAVIS_OS_NAME" = "osx" ]];then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" = "osx" ]];then brew install --force bison flex icu4c glib swig python; fi
  - if [[ "$TRAVIS_OS_NAME" = "osx" ]];then export "PATH=$(brew --prefix bison)/bin:$(brew --prefix icu4c)/bin:$PATH"; fi

script:
  - autoreconf -fvi
  - ./configure --disable-static --enable-all-tools --with-readline --with-unicode-handler=icu --enable-python-bindings
  - make -j4 V=1 VERBOSE=1
  - make check V=1 VERBOSE=1
  - sudo make install

notifications:
    irc:
        channels:
            - secure: "FWjUrhqWeVjjJnLQb7CwxxztJgE6OgL5h39MRzF9LKjGML1kd2GEBrJBITzdWhLvwJhkhY1so4zZ73MuxUJGSNOKagvt2qamliGIx/IbgAwlTlwQtR8ya0qdV6ITWMXa5pm86RoFrpnD+45Bitu7R0sPgHNNFImBbWmTKntiIw6xvvHklIsIvxWvMNny/FNEl95ZCTz8SkPeFYyRbdM2krRsKoPefI8kbCAaBdbXgo6zSboGkZinkDCXDJbn9cOeb06nBSeMd9SWzZSyx2DP1L8KhGvCnegwahN6bVYAcWZ5cCYDkB35pW0Of81siJzYMjr7yLggL27eROG3CgCeK8x9jg5rJW2IhZkxECYzAKftQPPALXkBOiEtFABhAdtBa316W5uz+XasIG9COvUSzh2f7s7M1cqkhmLTi3PLP8JcjViyV9PgH54sP+pjGilaXEGkAH++Rtj/0Jc3edTapZipEnZnAPO/3idCloJ7+goWzXcIJeLtQA8pgqi3wFlHguzvMDJIAjlrj7WM5Lzi4ZEzudlggdq3VE2K4jlBOqt3jKCwYOxdpsnzXi9dX/4mPzFnAM7AvTlankV2hg3E98zkDbUqcB56gf79S5Z4oAq71iXHyilPZ9EDf/RaUm+7tENAxB8WUVjLUpUcEH6y5C9i/TX20mUxivEWtjsq0jQ="
        on_failure: always
        on_success: never
# The irc channel is encrypted for hfst/hfst, so build notifications from forks won't show up on the IRC channel
# Encrypt with:
# $ gem install --user-install travis
# $ ~/.gem/ruby/*/bin/travis encrypt -r hfst/hfst 'chat.freenode.net#hfst'
