name: HFST CI Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: dependencies
      run: |
           sudo apt-get -qy update
           sudo apt-get -qfy install --no-install-recommends build-essential automake autotools-dev pkg-config python3-dev python3-setuptools swig bison flex libicu-dev libreadline-dev libtool zlib1g-dev
    - name: autoreconf
      run: autoreconf -fvi
    - name: configure
      run: ./configure --disable-static --enable-all-tools --with-readline --with-unicode-handler=icu --enable-python-bindings
    - name: build
      run: make -j4 V=1 VERBOSE=1
    - name: tests
      run: make check V=1 VERBOSE=1
    - name: make install
      run: sudo make install
